version: '3.4'

services:
  pmtDb:
    image: mongo
    ports:
        - 27017:27017
    volumes:
        - mongo_data:/data/db

  manager.api:
    image: ${DOCKER_REGISTRY-}managerapi
    build:
      context: .
      dockerfile: Services/Manager/Manager.API/Dockerfile
  
  project.api:
    image: ${DOCKER_REGISTRY-}projectapi
    build:
      context: .
      dockerfile: Services/Project/Project.API/Dockerfile

volumes:
  mongo_data: