version: '3.4'

services:
  pmtDb:
    container_name: pmtDb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  manager.api:
    container_name: manager.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://pmtDb:27017"
    depends_on:
      - pmtDb
    ports:
      - "8000:80"
